// Writes the Bridge's and the Extension's entry-origin constants from the one data
// file that defines them, so the two halves cannot disagree about which origins a
// Sign-in request may start from. Usage: node tools/generate.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const provider = "entra";
const dataFile = join("identity-providers", `${provider}.json`);

const header = (comment) =>
  `${comment} Generated by tools/generate.mjs from ${dataFile}. Do not edit.`;

function readEntryOrigins() {
  const data = JSON.parse(readFileSync(join(root, dataFile), "utf8"));
  const origins = data.entryOrigins;
  if (!Array.isArray(origins) || origins.length === 0) {
    throw new Error(`${dataFile}: entryOrigins must be a non-empty array`);
  }
  for (const origin of origins) {
    let parsed;
    try {
      parsed = new URL(origin);
    } catch {
      throw new Error(`${dataFile}: '${origin}' is not a URL`);
    }
    // Bare https origins only: the Swift constant force-unwraps these, the manifests
    // append '/*' to them, and an origin carrying a path would silently narrow both.
    if (parsed.protocol !== "https:" || parsed.origin !== origin) {
      throw new Error(`${dataFile}: '${origin}' is not a bare https origin`);
    }
  }
  return origins;
}

/** The provider's sign-in entry origins, exactly as the data file spells them. */
export const entryOrigins = readEntryOrigins();

/** The same origins as extension match patterns, for host_permissions and webRequest. */
export const entryOriginMatchPatterns = entryOrigins.map((origin) => `${origin}/*`);

// swift-format's TrailingComma rule wants the last element to carry a comma only in a
// literal it considers multiline, which a one-origin literal is not.
function swiftSource() {
  const comma = entryOrigins.length > 1 ? "," : "";
  const literals = entryOrigins.map(
    (origin, index) =>
      `    URL(string: "${origin}")!${index === entryOrigins.length - 1 ? comma : ","}`,
  );
  return [
    header("//"),
    "",
    "import Foundation",
    "",
    "/// The sign-in entry origins each identity provider adapter matches against.",
    "///",
    "/// Compiled in rather than read from a bundle resource: an ad-hoc-signed `.app`'s",
    "/// resources are writable by anyone who can reach it, and an editable entry-origin",
    "/// list is exactly what the Bridge must not have.",
    "public enum EntryOrigins {",
    "  /// Force-unwrapped because the generator parses every origin before writing this file.",
    `  public static let ${provider}: [URL] = [`,
    ...literals,
    "  ]",
    "}",
    "",
  ].join("\n");
}

// Prettier collapses an array literal that fits inside its print width, so match it
// here rather than depend on the Extension's toolchain to format a generated file.
function tsArray(name, values) {
  const items = values.map((value) => `"${value}"`);
  const oneLine = `export const ${name} = [${items.join(", ")}];`;
  if (oneLine.length <= 100) {
    return oneLine;
  }
  return [`export const ${name} = [`, ...items.map((item) => `  ${item},`), "];"].join("\n");
}

function typeScriptSource() {
  return [
    header("//"),
    "",
    "/** Bare origins, for the click-time check on the active tab's URL. */",
    tsArray("entryOrigins", entryOrigins),
    "",
    "/** Match patterns, for the webRequest listener's `urls` filter. */",
    tsArray("entryOriginMatchPatterns", entryOriginMatchPatterns),
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const outputs = [
    ["bridge/Sources/BridgeCore/Generated/EntryOrigins.swift", swiftSource()],
    ["extension/src/generated/entryOrigins.ts", typeScriptSource()],
  ];
  for (const [path, source] of outputs) {
    const file = join(root, path);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, source);
    console.log(`${dataFile} -> ${path}`);
  }
}
